from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted((item, item) for item in get_all_styles())


class Snippet(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    # title = models.CharField(max_length=100, default='hello')
    code = models.TextField()
    linenos = models.BooleanField(default=False)
    language = models.CharField(choices=LANGUAGE_CHOICES, default='python', max_length=100)
    style = models.CharField(choices=STYLE_CHOICES, default='friendly', max_length=100)

    class Meta:
        ordering = ('created',)


class SystemState(models.Model):
    systemId = models.IntegerField(default=0)
    from_date = models.DateTimeField(blank=True, null=True)
    to_date = models.DateTimeField(blank=True, null=True)
    patch = models.CharField(max_length=255, blank=True, null=True)
    patch_previous = models.CharField(max_length=255, blank=True, null=True)
    vv_count = models.IntegerField(default=0)
    vv_count_previous = models.IntegerField(default=0)
    vv_total_io = models.DecimalField(default=0, max_digits=15, decimal_places=3)
    port_total_io = models.DecimalField(default=0, max_digits=15, decimal_places=3)
    delayed_acks = models.IntegerField(default=0)
    delayed_acks_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_over_16s = models.IntegerField(default=0)
    writes_over_32ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_over_64ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_over_128ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_over_256ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_over_512ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_over_1024ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_over_2048ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_over_4096ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_0_62ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_0_125ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_0_25ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_0_5ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_0_1ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_1_2ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_2_4ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_4_8ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_8_16ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_16_32ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_32_64ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_64_128ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_128_256ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_256_512ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_512_1024ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_1024_2048ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_2048_4096ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_4096_8192ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_8192_16384ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_16384_32768ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    writes_between_32768_65536ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_over_32ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_over_64ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_over_128ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_over_256ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_over_512ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_over_1024ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_over_2048ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_over_4096ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_0_62ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_0_125ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_0_25ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_0_5ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_0_1ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_1_2ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_2_4ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_4_8ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_8_16ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_16_32ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_32_64ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_64_128ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_128_256ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_256_512ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_512_1024ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_1024_2048ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_2048_4096ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_4096_8192ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_8192_16384ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_16384_32768ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    reads_between_32768_65536ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_over_32ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_over_64ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_over_128ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_over_256ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_over_512ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_over_1024ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_over_2048ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_over_4096ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_0_62ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_0_125ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_0_25ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_0_5ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_0_1ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_1_2ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_2_4ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_4_8ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_8_16ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_16_32ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_32_64ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_64_128ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_128_256ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_256_512ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_512_1024ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_1024_2048ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_2048_4096ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_4096_8192ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_8192_16384ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_16384_32768ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    rw_between_32768_65536ms_pct = models.DecimalField(max_digits=6, decimal_places=3)
    read_bandwidth_mbps = models.DecimalField(max_digits=15, decimal_places=10)
    write_bandwidth_mbps = models.DecimalField(max_digits=15, decimal_places=10)
    total_bandwidth_mbps = models.DecimalField(max_digits=15, decimal_places=10)
    cpu_system_avg = models.IntegerField(default=0)
    cpu_user_avg = models.IntegerField(default=0)
    cpu_total_avg = models.IntegerField(default=0)
    cpu_system_max_pct = models.IntegerField(default=0)
    cpu_user_max_pct = models.IntegerField(default=0)
    cpu_total_max_pct = models.IntegerField(default=0)
    io_read_size_avg_kb = models.DecimalField(max_digits=15, decimal_places=10)
    io_write_size_avg_kb = models.DecimalField(max_digits=15, decimal_places=10)
    io_total_size_avg_kb = models.DecimalField(max_digits=15, decimal_places=10)
    dedupe_size = models.DecimalField(max_digits=15, decimal_places=10)
    node_last_online = models.DateTimeField(blank=True, null=True)
    node_offline_count = models.IntegerField(default=0)
    node_missing_count = models.IntegerField(default=0)
    dedupe_prev_size = models.DecimalField(max_digits=15, decimal_places=10)


class SystemOverview(models.Model):
    serial = models.IntegerField(default=0)
    company = models.CharField(max_length=255, blank=True, null=True)
    model = models.CharField(max_length=255, blank=True, null=True)
    updated_date = models.DateTimeField(blank=True, null=True)
    installed_date = models.DateTimeField(blank=True, null=True)
    storage_capacity = models.DecimalField(max_digits=15, decimal_places=10)
    storage_free_pct = models.DecimalField(max_digits=15, decimal_places=10)
    storage_capacity_fc = models.DecimalField(max_digits=15, decimal_places=10)
    storage_capacity_nl = models.DecimalField(max_digits=15, decimal_places=10)
    storage_capacity_ssd = models.DecimalField(max_digits=15, decimal_places=10)
    dedupe_ratio = models.DecimalField(max_digits=15, decimal_places=10)
    tdvv_count = models.IntegerField(default=0)
    tdvv_capacity = models.DecimalField(max_digits=15, decimal_places=10)
    records = models.ManyToManyField(SystemState, blank=True)
