# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(default=b'hello', max_length=100),
        ),
    ]
