# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_remove_test_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
